server:
  port: 8888

spring:
  application:
    name: oss

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
      enabled: true

  cloud:
    nacos:
      discovery:
        server-addr: *****************


END_POIND: *****************
ACCESS_KEY_ID: *****************
ACCESS_KEY_SECRET: *****************
BUCKET_NAME: *****************
ROLE_ARN: *****************
logging:
  level:
    root: warn
    com.subway: info
  file:
    path: log/oss

#涛
appid: *****************
secret: *****************


#appid: *****************
#secret: *****************
