server:
  port: 8001

spring:
  application:
    name: login

  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: *****************
    username: *****************
    password: *****************


  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: *****************

  cloud:
    nacos:
      discovery:
        server-addr: *****************

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.subway.entity

logging:
  level:
    root: warn
    com.subway: info
  file:
    path: log/login

#涛
appid: *****************
secret: *****************


#appid: wxca784963cec0dbd7
#secret: 51706c83f79ae5565e07896fb9fec0dc

