server:
  port: 8003

spring:
  application:
    name: maintenance

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://*****************/subway?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: *****************
    password: **********************************
    hikari:
      max-lifetime: 500000

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: *****************

  profiles:
    active: dev

  cloud:
    nacos:
      discovery:
        server-addr: *****************
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.subway.entity

appid: *****************
secret: *****************

logging:
  level:
    root: warn
    com.subway: info
  file:
    path: log/repair
