server:
  port: 8000

spring:
  application:
    name: control-center

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: *****************
    username: root
    password: *****************
    hikari:
      max-lifetime: 500000

  thymeleaf:
    prefix: classpath:/
    check-template-location: true
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false


  cloud:
    nacos:
      discovery:
        server-addr: *****************
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.subway.entity

#appid: *****************
#secret: *****************

#涛
appid: *****************
secret: *****************

logging:
  level:
    root: warn
    com.subway: info
  file:
    path: log/control
