server:
  port: 8000

spring:
  application:
    name: control-center

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.4.80.204:3306/subway?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: Zx991026.Zy
    hikari:
      max-lifetime: 500000

  thymeleaf:
    prefix: classpath:/
    check-template-location: true
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false


  cloud:
    nacos:
      discovery:
        server-addr: 121.4.80.204:8848
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.subway.entity

#appid: wxca784963cec0dbd7
#secret: 51706c83f79ae5565e07896fb9fec0dc

#涛
appid: wxb9be6f412ede54f8
secret: 65dde8526087353aa389d4761da6107e

logging:
  level:
    root: warn
    com.subway: info
  file:
    path: log/control